module.exports = {
  Balls: [
    "introduction",
    {
      type: "category",
      label: "Installation",
      items: [
        "installation/quick-start",
        "installation/install",
        "installation/manual",
        "installation/build-from-source",
        "installation/hive",
        // "installation/docker",
        // "installation/bee-clef",
        // "installation/connectivity",
        "installation/fund-your-node",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Working With Ant",
      items: [
        "working-with-ant/configuration",
        "working-with-ant/debug-api",
        "working-with-ant/logs-and-files",
        "working-with-ant/ant-tools",
        "working-with-ant/cashing-out",
        "working-with-ant/monitoring",
        "working-with-ant/backups",
        "working-with-ant/upgrade",
        "working-with-ant/uninstalling-ant",
        "working-with-ant/introduction",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Access the Sana",
      items: [
        "access-the-sana/introduction",
        "access-the-sana/upload-and-download",
        "access-the-sana/upload-a-directory",
        "access-the-sana/store-with-encryption",
        "access-the-sana/host-your-website",
        "access-the-sana/syncing",
        "access-the-sana/keep-your-data-alive",
        "access-the-sana/pinning",
        "access-the-sana/light-nodes",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Dapps on Sana",
      items: [
        "dapps-on-sana/introduction",
        "dapps-on-sana/develop-on-bee",
        "dapps-on-sana/bee-js",
        "dapps-on-sana/chunk-types",
        "dapps-on-sana/feeds",
        "dapps-on-sana/pss",
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: ["api-reference/api-reference"],
    },
    {
      type: "category",
      label: "Ant Developers",
      items: ["ant-developers/useful-dev-info"],
    },
    {
      type: "category",
      label: "FAQ",
      items: ["FAQ"],
    },
    {
      type: "category",
      label: "Join Us",
      items: ["community/community", "community/awesome-swarm"],
      collapsed: false,
    },
  ],
};
